import type { Service, Project, Testimonial, PricingPlan, TeamMember, ProcessStep } from "@/types";

export const services: Service[] = [
  {
    id: "web-development",
    icon: "💻",
    title: "Web Development",
    description: "Blazing-fast, scalable web applications built with modern technologies and best practices.",
    features: ["Next.js / React", "Node.js APIs", "Database Design", "CMS Integration", "Performance Optimization"],
    color: "from-purple-500 to-indigo-500",
    image: "https://images.unsplash.com/photo-1461749280684-dccba630e2f6?w=800&q=80",
  },
  {
    id: "crm",
    icon: "🔄",
    title: "CRM Solutions",
    description: "Custom CRM systems to manage customer relationships, streamline sales, and boost business growth.",
    features: ["Customer Management", "Sales Pipeline", "Analytics Dashboard", "Automation Tools", "Integration Support"],
    color: "from-blue-500 to-cyan-500",
    image: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800&q=80",
  },
  {
    id: "app-dev",
    icon: "📲",
    title: "App Development",
    description: "Native and cross-platform mobile apps with seamless experiences across all devices.",
    features: ["React Native", "iOS & Android", "API Integration", "App Store Launch", "Push Notifications"],
    color: "from-pink-500 to-rose-500",
    image: "https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?w=800&q=80",
  },
];

export const projects: Project[] = [
  {
    id: "almishk",
    title: "Al Mishk",
    category: "E-Commerce",
    tags: ["React", "Node.js", "MongoDB", "WhatsApp API"],
    description: "Premium attar & perfume e-commerce platform with full product catalogue, cart, wishlist, order tracking, combo deals, and WhatsApp ordering. Live at almishk.in.",
    image: "https://images.unsplash.com/photo-1588405748880-12d1d2a59d75?w=800&q=80",
    link: "https://almishk.in",
  },
  {
    id: "nasskhub",
    title: "Nassk Hub",
    category: "E-Commerce",
    tags: ["React", "Node.js", "Tailwind CSS", "E-Commerce"],
    description: "E-commerce platform for custom printing & branded merchandise — business cards, banners, gift items, and packaging with product customization.",
    image: "https://images.unsplash.com/photo-1611224923853-80b023f02d71?w=800&q=80",
    link: "https://nasskhub.vercel.app",
  },
  {
    id: "panchaiyat",
    title: "Panchaiyat Cafe",
    category: "Web Design",
    tags: ["React", "Vite", "Tailwind CSS", "Zomato"],
    description: "Full-stack website for a Delhi-based cloud kitchen with tabbed menu, add-to-cart, Zomato order integration, and a bold late-night brand identity. Live at panchaiyatcafe.in.",
    image: "https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=800&q=80",
    link: "https://panchaiyatcafe.in",
  },
  {
    id: "globetrotter",
    title: "Globe Trotter",
    category: "Web Design",
    tags: ["React", "Vite", "Tailwind CSS", "WhatsApp API"],
    description: "India's trusted travel partner site featuring curated international tour packages, destination cards with pricing, WhatsApp booking, and testimonials.",
    image: "https://images.unsplash.com/photo-1488085061387-422e29b40080?w=800&q=80",
    link: "https://globe-trotter-ui.vercel.app",
  },
  {
    id: "b2bmarketplace",
    title: "B2B Marketplace",
    category: "Web Development",
    tags: ["React", "Node.js", "MongoDB", "Auth"],
    description: "Verified B2B marketplace connecting global buyers and sellers with business verification flow, subscription-gated listings, and secure auth.",
    image: "https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=800&q=80",
    link: "https://marketplace-d5rm.vercel.app",
  },
  {
    id: "driveyouu",
    title: "DriveYouu",
    category: "App Development",
    tags: ["React", "Node.js", "Maps API", "MongoDB"],
    description: "On-demand cab booking web application with ride scheduling, driver-passenger matching, and location-based pickup and drop services.",
    image: "https://images.unsplash.com/photo-1449965408869-eaa3f722e40d?w=800&q=80",
    link: "https://driveyouu.vercel.app",
  },
];

export const testimonials: Testimonial[] = [
  {
    id: "1",
    name: "Zara Ahmed",
    role: "Owner",
    company: "Al Mishk",
    avatar: "/avatars/zara.jpg",
    content: "TheWebYatra built our entire attar & perfume store from scratch. The WhatsApp ordering, combo deals and product catalogue are exactly what we needed. Sales went up significantly after launch. Highly recommend!",
    rating: 5,
  },
  {
    id: "2",
    name: "Rohan Sharma",
    role: "Founder",
    company: "Panchaiyat Cafe",
    avatar: "/avatars/rohan.jpg",
    content: "Our cloud kitchen website looks stunning and the Zomato integration works perfectly. Customers find us easily and the menu system is super smooth. Delivered on time and exactly as promised.",
    rating: 5,
  },
  {
    id: "3",
    name: "Priya Verma",
    role: "Manager",
    company: "Globe Trotter",
    avatar: "/avatars/priya.jpg",
    content: "The travel packages website they built for us is professional and easy to navigate. WhatsApp booking integration brought us more enquiries within the first week. Really happy with the work.",
    rating: 5,
  },
  {
    id: "4",
    name: "Amir Khan",
    role: "CEO",
    company: "Nassk Hub",
    avatar: "/avatars/amir.jpg",
    content: "Custom printing platform with product customization, cart and order management — all built cleanly and quickly. The team understood exactly what we needed and delivered without delays.",
    rating: 5,
  },
  {
    id: "5",
    name: "Deepak Nair",
    role: "Director",
    company: "DriveYouu",
    avatar: "/avatars/deepak.jpg",
    content: "Real-time cab booking with driver matching and Maps integration — built on a tight timeline and works flawlessly. Very professional team and clean code. Will work with them again.",
    rating: 5,
  },
];

export const pricingPlans: PricingPlan[] = [
  {
    id: "starter",
    name: "Starter",
    price: "₹49,999",
    period: "one-time",
    description: "Perfect for small businesses and startups launching their digital presence.",
    features: [
      "5-Page Custom Website",
      "Mobile Responsive Design",
      "Basic SEO Setup",
      "Contact Form Integration",
      "2 Months Free Support",
      "Google Analytics Setup",
      "SSL Certificate",
      "Source Code Handover",
    ],
    highlighted: false,
    cta: "Get a Quote",
  },
  {
    id: "growth",
    name: "Growth",
    price: "₹1,19,999",
    period: "one-time",
    description: "For growing businesses ready to scale with a powerful digital platform.",
    features: [
      "Up to 20 Pages",
      "Custom UI/UX Design",
      "Advanced SEO Package",
      "CMS Integration",
      "E-Commerce Ready",
      "Performance Optimization",
      "4 Months Free Support",
      "Analytics Dashboard",
      "Social Media Integration",
      "Priority Support",
      "Speed & Core Web Vitals",
    ],
    highlighted: true,
    cta: "Get a Quote",
  },
  {
    id: "enterprise",
    name: "Enterprise",
    price: "Custom",
    period: "project",
    description: "Full-scale digital solutions for enterprise-level requirements.",
    features: [
      "Unlimited Pages",
      "Custom Web Application",
      "Full Brand Identity",
      "Advanced E-Commerce",
      "SEO + Content Strategy",
      "Mobile App Development",
      "AI Integration",
      "Dedicated Project Manager",
      "12 Months Support",
      "SLA Guarantee",
      "Custom Integrations",
      "Team Training",
    ],
    highlighted: false,
    cta: "Let's Talk",
  },
];

export const processSteps: ProcessStep[] = [
  {
    id: "discover",
    step: 1,
    title: "Discover",
    description: "We explore your goals, target audience, and competitive landscape to chart the perfect route for your digital journey.",
    icon: "🔍",
  },
  {
    id: "design",
    step: 2,
    title: "Design",
    description: "Our designers craft pixel-perfect wireframes and visual designs that align with your brand and delight your users.",
    icon: "✏️",
  },
  {
    id: "develop",
    step: 3,
    title: "Develop",
    description: "We build your product with clean, scalable code using modern tech stacks — tested, optimized and production-ready.",
    icon: "⚡",
  },
  {
    id: "launch",
    step: 4,
    title: "Launch",
    description: "We deploy your project to the world with full CI/CD pipelines, monitoring, and zero-downtime deployment strategies.",
    icon: "🚀",
  },
  {
    id: "support",
    step: 5,
    title: "Support",
    description: "The journey doesn't end at launch. We provide ongoing support, analytics review, and continuous improvements.",
    icon: "🛡️",
  },
];

export const teamMembers: TeamMember[] = [
  {
    id: "inayat",
    name: "Mohd Inayat",
    role: "Founder & Full-Stack Developer",
    bio: "Full-Stack & Java Developer building scalable web apps and AI-integrated products. MERN Stack specialist. Built Al Mishk, Panchaiyat Cafe, Globe Trotter and more. Based in Delhi.",
    avatar: "/team/inayat.jpg",
    socials: {
      twitter: "https://twitter.com/inayatshaykh",
      linkedin: "https://www.linkedin.com/in/inayatshaykh/",
      github: "https://github.com/inayatshaykh",
    },
  },
  {
    id: "priya",
    name: "Priya Nair",
    role: "Head of Design",
    bio: "UI/UX expert with a sharp eye for detail. Bridges beautiful design and functional user experiences across web and mobile.",
    avatar: "/team/priya.jpg",
    socials: {
      linkedin: "#",
    },
  },
  {
    id: "dev",
    name: "Dev Kapoor",
    role: "Lead Backend Developer",
    bio: "Node.js & database architect. Specializes in scalable APIs, cloud infrastructure, and performance optimization.",
    avatar: "/team/dev.jpg",
    socials: {
      github: "#",
      linkedin: "#",
    },
  },
  {
    id: "sara",
    name: "Sara Khan",
    role: "SEO & Growth Lead",
    bio: "Data-driven growth strategist who's helped 50+ brands rank on page 1. Expert in technical SEO, content strategy, and conversion optimization.",
    avatar: "/team/sara.jpg",
    socials: {
      linkedin: "#",
    },
  },
];

export const techStack = [
  { name: "Next.js", icon: "⬡" },
  { name: "React", icon: "⚛" },
  { name: "TypeScript", icon: "TS" },
  { name: "Node.js", icon: "⬢" },
  { name: "Tailwind CSS", icon: "◈" },
  { name: "PostgreSQL", icon: "⊕" },
  { name: "Shopify", icon: "◆" },
  { name: "Figma", icon: "◎" },
  { name: "AWS", icon: "☁" },
  { name: "Vercel", icon: "▲" },
  { name: "React Native", icon: "◉" },
  { name: "GraphQL", icon: "◈" },
];

export const trustedLogos = [
  "Al Mishk", "Panchaiyat Cafe", "Nassk Hub", "Globe Trotter",
  "DriveYouu", "B2B Market", "Oasis Infobyte", "CodSoft",
  "Al Mishk", "Panchaiyat Cafe", "Nassk Hub", "Globe Trotter",
  "DriveYouu", "B2B Market", "Oasis Infobyte", "CodSoft",
];
