import type { Service, Project, Testimonial, PricingPlan, TeamMember, ProcessStep } from "@/types";

export const services: Service[] = [
  {
    id: "web-design",
    icon: "✦",
    title: "Web Design",
    description: "Pixel-perfect, conversion-focused designs that tell your brand story and captivate your audience.",
    features: ["UI/UX Design", "Brand Identity", "Wireframing", "Prototyping", "Design Systems"],
    color: "from-blue-500 to-cyan-500",
  },
  {
    id: "web-development",
    icon: "⟨/⟩",
    title: "Web Development",
    description: "Blazing-fast, scalable web applications built with modern technologies and best practices.",
    features: ["Next.js / React", "Node.js APIs", "Database Design", "CMS Integration", "Performance Optimization"],
    color: "from-purple-500 to-indigo-500",
  },
  {
    id: "ecommerce",
    icon: "◈",
    title: "E-Commerce",
    description: "High-converting online stores that turn visitors into loyal customers at scale.",
    features: ["Shopify / WooCommerce", "Custom Checkout", "Payment Integration", "Inventory System", "Analytics"],
    color: "from-pink-500 to-rose-500",
  },
  {
    id: "seo",
    icon: "◎",
    title: "SEO Optimization",
    description: "Data-driven SEO strategies that put your business at the top of search results.",
    features: ["Technical SEO", "Content Strategy", "Keyword Research", "Link Building", "Analytics & Reports"],
    color: "from-green-500 to-emerald-500",
  },
  {
    id: "branding",
    icon: "◆",
    title: "Branding",
    description: "Build a memorable brand identity that resonates, differentiates, and endures.",
    features: ["Logo Design", "Brand Guidelines", "Color Systems", "Typography", "Brand Strategy"],
    color: "from-yellow-500 to-orange-500",
  },
  {
    id: "app-dev",
    icon: "⬡",
    title: "App Development",
    description: "Native and cross-platform mobile apps with seamless experiences across all devices.",
    features: ["React Native", "iOS & Android", "API Integration", "App Store Launch", "Push Notifications"],
    color: "from-violet-500 to-purple-500",
  },
];

export const projects: Project[] = [
  {
    id: "almishk",
    title: "Al Mishk",
    category: "E-Commerce",
    tags: ["React", "Node.js", "MongoDB", "WhatsApp API"],
    description: "Premium attar & perfume e-commerce platform with full product catalogue, cart, wishlist, order tracking, combo deals, and WhatsApp ordering. Live at almishk.in.",
    image: "/projects/almishk.jpg",
    link: "https://almishk.in",
  },
  {
    id: "nasskhub",
    title: "Nassk Hub",
    category: "E-Commerce",
    tags: ["React", "Node.js", "Tailwind CSS", "E-Commerce"],
    description: "E-commerce platform for custom printing & branded merchandise — business cards, banners, gift items, and packaging with product customization.",
    image: "/projects/nasskhub.jpg",
    link: "https://nasskhub.vercel.app",
  },
  {
    id: "panchaiyat",
    title: "Panchaiyat Cafe",
    category: "Web Design",
    tags: ["React", "Vite", "Tailwind CSS", "Zomato"],
    description: "Full-stack website for a Delhi-based cloud kitchen with tabbed menu, add-to-cart, Zomato order integration, and a bold late-night brand identity. Live at panchaiyatcafe.in.",
    image: "/projects/panchaiyat.jpg",
    link: "https://panchaiyatcafe.in",
  },
  {
    id: "globetrotter",
    title: "Globe Trotter",
    category: "Web Design",
    tags: ["React", "Vite", "Tailwind CSS", "WhatsApp API"],
    description: "India's trusted travel partner site featuring curated international tour packages, destination cards with pricing, WhatsApp booking, and testimonials.",
    image: "/projects/globetrotter.jpg",
    link: "https://globe-trotter-ui.vercel.app",
  },
  {
    id: "b2bmarketplace",
    title: "B2B Marketplace",
    category: "Web Development",
    tags: ["React", "Node.js", "MongoDB", "Auth"],
    description: "Verified B2B marketplace connecting global buyers and sellers with business verification flow, subscription-gated listings, and secure auth.",
    image: "/projects/b2b.jpg",
    link: "https://marketplace-d5rm.vercel.app",
  },
  {
    id: "driveyouu",
    title: "DriveYouu",
    category: "App Development",
    tags: ["React", "Node.js", "Maps API", "MongoDB"],
    description: "On-demand cab booking web application with ride scheduling, driver-passenger matching, and location-based pickup and drop services.",
    image: "/projects/driveyouu.jpg",
    link: "https://driveyouu.vercel.app",
  },
];

export const testimonials: Testimonial[] = [
  {
    id: "1",
    name: "Priya Sharma",
    role: "CEO",
    company: "LuxeStay Hotels",
    avatar: "/avatars/priya.jpg",
    content: "TheWebYatra transformed our entire online presence. Bookings increased 340% within 3 months of launch. The team's attention to detail and the journey-focused process made everything smooth.",
    rating: 5,
  },
  {
    id: "2",
    name: "Marcus Chen",
    role: "Founder",
    company: "Verdant Organics",
    avatar: "/avatars/marcus.jpg",
    content: "From brand identity to a fully-working Shopify store — they delivered beyond expectations. Our conversion rate doubled. Best investment we've made for the business.",
    rating: 5,
  },
  {
    id: "3",
    name: "Aisha Patel",
    role: "CTO",
    company: "NexaFinance",
    avatar: "/avatars/aisha.jpg",
    content: "The technical depth of the team is impressive. They built our entire fintech dashboard in 6 weeks, clean code, great documentation. We've launched to 50k+ users without a single outage.",
    rating: 5,
  },
  {
    id: "4",
    name: "James O'Brien",
    role: "Marketing Director",
    company: "SolarTech Solutions",
    avatar: "/avatars/james.jpg",
    content: "SEO results speak for themselves: from page 4 to #1 ranking in 4 months. The web redesign brought us 5x more qualified leads. Absolutely incredible team.",
    rating: 5,
  },
  {
    id: "5",
    name: "Nadia Volkov",
    role: "Head of Product",
    company: "UrbanFit",
    avatar: "/avatars/nadia.jpg",
    content: "They built our React Native app from scratch and handled the App Store submissions. Communication was flawless throughout the journey. 10/10 would recommend.",
    rating: 5,
  },
];

export const pricingPlans: PricingPlan[] = [
  {
    id: "starter",
    name: "Starter",
    price: "₹49,999",
    period: "one-time",
    description: "Perfect for small businesses and startups launching their digital presence.",
    features: [
      "5-Page Custom Website",
      "Mobile Responsive Design",
      "Basic SEO Setup",
      "Contact Form Integration",
      "2 Months Free Support",
      "Google Analytics Setup",
      "SSL Certificate",
      "Source Code Handover",
    ],
    highlighted: false,
    cta: "Get a Quote",
  },
  {
    id: "growth",
    name: "Growth",
    price: "₹1,19,999",
    period: "one-time",
    description: "For growing businesses ready to scale with a powerful digital platform.",
    features: [
      "Up to 20 Pages",
      "Custom UI/UX Design",
      "Advanced SEO Package",
      "CMS Integration",
      "E-Commerce Ready",
      "Performance Optimization",
      "4 Months Free Support",
      "Analytics Dashboard",
      "Social Media Integration",
      "Priority Support",
      "Speed & Core Web Vitals",
    ],
    highlighted: true,
    cta: "Get a Quote",
  },
  {
    id: "enterprise",
    name: "Enterprise",
    price: "Custom",
    period: "project",
    description: "Full-scale digital solutions for enterprise-level requirements.",
    features: [
      "Unlimited Pages",
      "Custom Web Application",
      "Full Brand Identity",
      "Advanced E-Commerce",
      "SEO + Content Strategy",
      "Mobile App Development",
      "AI Integration",
      "Dedicated Project Manager",
      "12 Months Support",
      "SLA Guarantee",
      "Custom Integrations",
      "Team Training",
    ],
    highlighted: false,
    cta: "Let's Talk",
  },
];

export const processSteps: ProcessStep[] = [
  {
    id: "discover",
    step: 1,
    title: "Discover",
    description: "We explore your goals, target audience, and competitive landscape to chart the perfect route for your digital journey.",
    icon: "🔍",
  },
  {
    id: "design",
    step: 2,
    title: "Design",
    description: "Our designers craft pixel-perfect wireframes and visual designs that align with your brand and delight your users.",
    icon: "✏️",
  },
  {
    id: "develop",
    step: 3,
    title: "Develop",
    description: "We build your product with clean, scalable code using modern tech stacks — tested, optimized and production-ready.",
    icon: "⚡",
  },
  {
    id: "launch",
    step: 4,
    title: "Launch",
    description: "We deploy your project to the world with full CI/CD pipelines, monitoring, and zero-downtime deployment strategies.",
    icon: "🚀",
  },
  {
    id: "support",
    step: 5,
    title: "Support",
    description: "The journey doesn't end at launch. We provide ongoing support, analytics review, and continuous improvements.",
    icon: "🛡️",
  },
];

export const teamMembers: TeamMember[] = [
  {
    id: "inayat",
    name: "Mohd Inayat",
    role: "Founder & Full-Stack Developer",
    bio: "Full-Stack & Java Developer building scalable web apps and AI-integrated products. MERN Stack specialist. Built Al Mishk, Panchaiyat Cafe, Globe Trotter and more. Based in Delhi.",
    avatar: "/team/inayat.jpg",
    socials: {
      twitter: "https://twitter.com/inayatshaykh",
      linkedin: "https://www.linkedin.com/in/inayatshaykh/",
      github: "https://github.com/inayatshaykh",
    },
  },
  {
    id: "priya",
    name: "Priya Nair",
    role: "Head of Design",
    bio: "UI/UX expert with a sharp eye for detail. Bridges beautiful design and functional user experiences across web and mobile.",
    avatar: "/team/priya.jpg",
    socials: {
      linkedin: "#",
    },
  },
  {
    id: "dev",
    name: "Dev Kapoor",
    role: "Lead Backend Developer",
    bio: "Node.js & database architect. Specializes in scalable APIs, cloud infrastructure, and performance optimization.",
    avatar: "/team/dev.jpg",
    socials: {
      github: "#",
      linkedin: "#",
    },
  },
  {
    id: "sara",
    name: "Sara Khan",
    role: "SEO & Growth Lead",
    bio: "Data-driven growth strategist who's helped 50+ brands rank on page 1. Expert in technical SEO, content strategy, and conversion optimization.",
    avatar: "/team/sara.jpg",
    socials: {
      linkedin: "#",
    },
  },
];

export const techStack = [
  { name: "Next.js", icon: "⬡" },
  { name: "React", icon: "⚛" },
  { name: "TypeScript", icon: "TS" },
  { name: "Node.js", icon: "⬢" },
  { name: "Tailwind CSS", icon: "◈" },
  { name: "PostgreSQL", icon: "⊕" },
  { name: "Shopify", icon: "◆" },
  { name: "Figma", icon: "◎" },
  { name: "AWS", icon: "☁" },
  { name: "Vercel", icon: "▲" },
  { name: "React Native", icon: "◉" },
  { name: "GraphQL", icon: "◈" },
];

export const trustedLogos = [
  "Al Mishk", "Panchaiyat Cafe", "Nassk Hub", "Globe Trotter",
  "DriveYouu", "B2B Market", "Oasis Infobyte", "CodSoft",
  "Al Mishk", "Panchaiyat Cafe", "Nassk Hub", "Globe Trotter",
  "DriveYouu", "B2B Market", "Oasis Infobyte", "CodSoft",
];
